services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:passer0412@db:5432/even_221?schema=public
      PORT: 3001
      DB_MAX_RETRIES: 20
      DB_RETRY_DELAY_MS: 3000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer0412
      POSTGRES_DB: even_221
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
